# .github/workflows/branch-test.yml
name: Branch Test Workflow

on:
  push:
    branches: [ main, master, develop, 'feature/*' ]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: mainブランチ
      run: echo "mainブランチのworkflow"